# Generated by Django 3.1 on 2021-01-23 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfferedAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.IntegerField()),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email_1', models.EmailField(max_length=254)),
                ('email_2', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Privileges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Egresado', 'Egresado'), ('Equipo Alumni', 'Equipo Alumni'), ('Cliente Interno', 'Cliente Interno')], default='Egresado', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('facultad', models.CharField(choices=[('Escuela de Negocios', 'Escuela de Negocios'), ('Facultad de Derecho', 'Facultad de Derecho'), ('Facultad de Ingeniería y Ciencias', 'Facultad de Ingeniería y Ciencias'), ('Facultad Artes Liberales', 'Facultad Artes Liberales'), ('Escuela de Gobierno', 'Escuela de Gobierno'), ('Escuela de Psicología', 'Escuela de Psicología'), ('Escuela de Comunicaciones y Periodismo', 'Escuela de Comunicaciones y Periodismo'), ('DesignLab', 'DesignLab')], max_length=40)),
                ('description', models.TextField(blank=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('is_activated', models.BooleanField(default=False)),
                ('csv_file', models.FileField(upload_to='surveys_csvs/')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyQuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offered_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.offeredanswer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.question')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.survey')),
            ],
            options={
                'unique_together': {('survey', 'question', 'offered_answer')},
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.question')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.survey')),
            ],
            options={
                'unique_together': {('survey', 'question')},
            },
        ),
        migrations.CreateModel(
            name='QuerySurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.question')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.survey')),
            ],
            options={
                'unique_together': {('survey', 'query')},
            },
        ),
        migrations.CreateModel(
            name='PrivilegesQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privileges', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.privileges')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.question')),
            ],
            options={
                'unique_together': {('privileges', 'query')},
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True)),
                ('offered_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.offeredanswer')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.person')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.question')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.survey')),
            ],
            options={
                'unique_together': {('survey', 'question', 'offered_answer', 'person')},
            },
        ),
    ]
