# Generated by Django 3.1 on 2021-01-25 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('period', models.DateField()),
            ],
        ),
        migrations.RenameModel(
            old_name='QuerySurvey',
            new_name='QuerySurveyQuestion',
        ),
        migrations.AddField(
            model_name='query',
            name='graph_type',
            field=models.CharField(default='default', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='querysurveyquestion',
            name='survey_question',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveyquestion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(default='default', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='privilegesquery',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.query'),
        ),
        migrations.AlterField(
            model_name='query',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='query',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='querysurveyquestion',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.query'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterUniqueTogether(
            name='querysurveyquestion',
            unique_together={('survey_question', 'query')},
        ),
        migrations.RemoveField(
            model_name='querysurveyquestion',
            name='survey',
        ),
        migrations.CreateModel(
            name='EquivalentQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eq_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eq_question', to='surveys.question')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='surveys.question')),
            ],
            options={
                'unique_together': {('question', 'eq_question')},
            },
        ),
        migrations.CreateModel(
            name='DashboardQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.dashboard')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.query')),
            ],
            options={
                'unique_together': {('dashboard', 'query')},
            },
        ),
    ]
