# Generated by Django 3.1 on 2021-02-18 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='privilege',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='surveys.privileges'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='privileges',
            name='type',
            field=models.IntegerField(choices=[(1, 'Egresado'), (3, 'Equipo Alumni'), (2, 'Corporativo UAI')], default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='description',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='query',
            name='graph_type',
            field=models.CharField(choices=[(0, 'Bar Chart'), (1, 'Comparative Bar Chart'), (2, 'Pie Chart'), (3, 'Table')], default=3, max_length=300),
        ),
        migrations.DeleteModel(
            name='PrivilegesQuery',
        ),
    ]
