# Generated by Django 3.1 on 2021-02-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_auto_20210217_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='include_nan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='query',
            name='percentage_values',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='query',
            name='graph_type',
            field=models.CharField(choices=[('Bar_Chart', 'Bar Chart'), ('Comparative_Bar_Chart', 'Comparative Bar Chart'), ('Pie_Chart', 'Pie Chart'), ('Table', 'Table')], default='Table', max_length=300),
        ),
    ]
