# Generated by Django 3.1 on 2021-03-09 07:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_auto_20210224_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2021, 3, 9)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='query',
            name='privilege',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='surveys.privileges'),
        ),
    ]
